name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Configure Firebase Credentials
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase-credentials.json

      - name: Deploy Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-credentials.json
        run: firebase deploy --only hosting
